# Generated by Django 3.2.4 on 2021-09-07 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageID', models.CharField(default='ID', max_length=30)),
                ('imageName', models.TextField(default='Name')),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
