# Generated by Django 3.2.4 on 2021-12-10 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_games'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificateID', models.CharField(default='ID', max_length=30)),
                ('certificateName', models.TextField(default='Name')),
                ('certificateDescription', models.TextField(default='Description')),
                ('certificateImage', models.ImageField(upload_to='img')),
            ],
        ),
    ]
